# Generated by Django 4.2.7 on 2025-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("address", models.TextField()),
                ("contact_person", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "industry_type",
                    models.CharField(
                        choices=[
                            ("MANUFACTURING", "Manufacturing"),
                            ("CONSTRUCTION", "Construction"),
                            ("TECHNOLOGY", "Technology"),
                            ("AUTOMOTIVE", "Automotive"),
                            ("ENERGY", "Energy & Utilities"),
                            ("TELECOMMUNICATIONS", "Telecommunications"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("established_year", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "companies",
                "ordering": ["name"],
            },
        ),
    ]
