# Generated by Django 4.2.7 on 2025-08-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="industry_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANUFACTURING", "Manufacturing"),
                    ("CONSTRUCTION", "Construction"),
                    ("TECHNOLOGY", "Technology"),
                    ("AUTOMOTIVE", "Automotive"),
                    ("ENERGY", "Energy & Utilities"),
                    ("TELECOMMUNICATIONS", "Telecommunications"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
