# Generated by Django 4.2.7 on 2025-07-28 07:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20, unique=True)),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("MECHANICAL", "BSc. Mechanical Engineering"),
                            ("ELECTRICAL", "BSc. Electrical Engineering"),
                            ("CIVIL", "BSc. Civil Engineering"),
                            ("COMPUTER", "BSc. Computer Science"),
                            ("CHEMICAL", "BSc. Chemical Engineering"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "year_of_study",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                (
                    "pt_phase",
                    models.CharField(
                        choices=[
                            ("PT1", "Practical Training 1"),
                            ("PT2", "Practical Training 2"),
                            ("PT3", "Practical Training 3"),
                        ],
                        max_length=3,
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("supervisor_name", models.CharField(max_length=100)),
                (
                    "supervisor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.company",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "user_profiles",
            },
        ),
    ]
