# Generated by Django 4.2.7 on 2025-07-28 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MECHANICAL", "BSc. Mechanical Engineering"),
                    ("ELECTRICAL", "BSc. Electrical Engineering"),
                    ("CIVIL", "BSc. Civil Engineering"),
                    ("COMPUTER", "BSc. Computer Science"),
                    ("CHEMICAL", "BSc. Chemical Engineering"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pt_phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PT1", "Practical Training 1"),
                    ("PT2", "Practical Training 2"),
                    ("PT3", "Practical Training 3"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="student_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="supervisor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="year_of_study",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
    ]
