# Generated by Django 4.2.7 on 2025-08-04 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MECHANICAL", "BSc. Mechanical Engineering"),
                    ("ELECTRICAL", "BSc. Electrical Engineering"),
                    ("CIVIL", "BSc. Civil Engineering"),
                    ("TEXTILE_DESIGN", "BSc. Textile Design"),
                    ("TEXTILE_ENGINEERING", "BSc. Textile Engineering"),
                    ("INDUSTRIAL", "BSc. Industrial Engineering"),
                    ("GEOMATIC", "BSc. Geomatic Engineering"),
                    ("CHEMICAL", "BSc. Chemical Engineering"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="year_of_study",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
