# Generated by Django 4.2.7 on 2025-08-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_program_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="company",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
