# Generated by Django 4.2.7 on 2025-07-29 03:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyreport",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="generalreport",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="mainjoboperation",
            options={"ordering": ["step_number"]},
        ),
        migrations.AlterModelOptions(
            name="weeklyreport",
            options={"ordering": ["-week_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="mainjoboperation",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="aienhancementlog",
            name="enhanced_text",
        ),
        migrations.RemoveField(
            model_name="aienhancementlog",
            name="original_text",
        ),
        migrations.RemoveField(
            model_name="aienhancementlog",
            name="prompt_used",
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="challenges_faced",
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="is_submitted",
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="skills_learned",
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="supervisor_feedback",
        ),
        migrations.RemoveField(
            model_name="dailyreport",
            name="weekly_report",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="is_ai_enhanced",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="learning_outcomes",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="main_job_description",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="main_job_title",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="objectives_met",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="status",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="submitted_at",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="weeklyreport",
            name="supervisor_comments",
        ),
        migrations.AddField(
            model_name="aienhancementlog",
            name="enhanced_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aienhancementlog",
            name="original_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weeklyreport",
            name="is_complete",
            field=models.BooleanField(
                default=False, help_text="True if all 5 days have reports"
            ),
        ),
        migrations.AlterField(
            model_name="aienhancementlog",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAILY", "Daily Report"),
                    ("WEEKLY", "Weekly Report"),
                    ("GENERAL", "General Report"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aienhancementlog",
            name="enhancement_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENHANCE", "Text Enhancement"),
                    ("SUGGEST", "Improvement Suggestions"),
                    ("GENERATE", "Content Generation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aienhancementlog",
            name="tokens_consumed",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="aienhancementlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_ai_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="description",
            field=models.TextField(help_text="Description of work done"),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="hours_spent",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Hours spent (0.5 to 12 hours)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="week_number",
            field=models.IntegerField(
                help_text="Week number for linking to weekly report"
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="achievements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="acknowledgments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="challenges_faced",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="company_overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="compiled_from",
            field=models.ManyToManyField(
                blank=True,
                related_name="legacy_compiled_reports",
                to="reports.weeklyreport",
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="conclusion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="introduction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="is_ai_enhanced",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="methodology",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="skills_acquired",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="training_objectives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_general_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="generalreport",
            name="word_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="operation_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="operation_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="outcome",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="safety_measures",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="step_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="time_spent",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="tools_used",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="weekly_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_operations",
                to="reports.weeklyreport",
            ),
        ),
        migrations.AlterField(
            model_name="weeklyreport",
            name="end_date",
            field=models.DateField(help_text="End date (Friday)"),
        ),
        migrations.AlterField(
            model_name="weeklyreport",
            name="start_date",
            field=models.DateField(help_text="Start date (Monday)"),
        ),
        migrations.AlterField(
            model_name="weeklyreport",
            name="total_hours",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="weeklyreport",
            name="week_number",
            field=models.IntegerField(
                help_text="Week number for linking to weekly report"
            ),
        ),
        migrations.AlterModelTable(
            name="aienhancementlog",
            table=None,
        ),
        migrations.AlterModelTable(
            name="dailyreport",
            table=None,
        ),
        migrations.AlterModelTable(
            name="generalreport",
            table=None,
        ),
        migrations.AlterModelTable(
            name="mainjoboperation",
            table=None,
        ),
        migrations.AlterModelTable(
            name="weeklyreport",
            table=None,
        ),
        migrations.CreateModel(
            name="MainJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(help_text="Title of the main job", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the main job"),
                ),
                (
                    "tools_equipment",
                    models.TextField(help_text="Tools, machinery, equipment used"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekly_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_jobs",
                        to="reports.weeklyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
