# Generated by Django 4.2.7 on 2025-07-29 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_dailyreport_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainjob",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="mainjob",
            name="tools_equipment",
        ),
        migrations.AddField(
            model_name="mainjob",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title of the main job for this week",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mainjoboperation",
            name="main_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="reports.mainjob",
            ),
        ),
        migrations.AddField(
            model_name="mainjoboperation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="mainjob",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the main job", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mainjob",
            name="weekly_report",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_job",
                to="reports.weeklyreport",
            ),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="operation_description",
            field=models.TextField(
                blank=True, help_text="Description of this operation step", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="step_number",
            field=models.IntegerField(
                blank=True, help_text="Step number in the operation sequence", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mainjoboperation",
            name="tools_used",
            field=models.TextField(
                blank=True,
                help_text="Tools, machinery, equipment used for this step",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mainjoboperation",
            unique_together={("main_job", "step_number")},
        ),
        migrations.RemoveField(
            model_name="mainjoboperation",
            name="operation_name",
        ),
        migrations.RemoveField(
            model_name="mainjoboperation",
            name="outcome",
        ),
        migrations.RemoveField(
            model_name="mainjoboperation",
            name="safety_measures",
        ),
        migrations.RemoveField(
            model_name="mainjoboperation",
            name="time_spent",
        ),
        migrations.RemoveField(
            model_name="mainjoboperation",
            name="weekly_report",
        ),
    ]
