# Generated by Django 4.2.7 on 2025-08-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_remove_mainjob_job_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginalUserInputs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_main_job_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "original_daily_reports",
                    models.JSONField(
                        default=dict, help_text="Original daily reports data"
                    ),
                ),
                (
                    "original_operations",
                    models.JSONField(
                        default=dict, help_text="Original operations data"
                    ),
                ),
                (
                    "enhancement_instructions",
                    models.TextField(
                        blank=True,
                        help_text="User's enhancement instructions",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "weekly_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_inputs",
                        to="reports.weeklyreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Original User Inputs",
                "verbose_name_plural": "Original User Inputs",
                "db_table": "original_user_inputs",
            },
        ),
    ]
